language: python
virt: vm

python:
  - "2.7"
  - "3.6"

cache:
  pip: true
  directories:
    - /home/travis/build/RedHatInsights/malware-detection-client/yara-4.1.0

install:
  - pip install -e .[dev]

script:
  - flake8 --ignore E501 --filename "*" src/
  - python -B -m pytest -v tests

before_script:
  - sudo apt-get install -y automake libtool make gcc pkg-config
  - wget -q https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.0.tar.gz -O - | tar zx
  - pushd yara-4.1.0 && ./bootstrap.sh && ./configure &&  make && sudo make install && popd
  - sudo sh -c 'echo "/usr/local/lib" >> /etc/ld.so.conf' && sudo ldconfig

notifications:
  email: false
