language: python

python:
  - "2.7"
  - "3.6"
  - "3.9"

cache:
  pip: true
  directories:
    - /home/travis/build/RedHatInsights/malware-detection-client/yara-4.1.0

install:
  - pip install -e .[dev]

script:
  - make test

before_script:
  - sudo apt-get install -y automake libtool make gcc pkg-config
  - wget -q https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.2.tar.gz -O - | tar zx
  - pushd yara-4.1.2 && ./bootstrap.sh && ./configure &&  make && sudo make install && popd
  - sudo sh -c 'echo "/usr/local/lib" >> /etc/ld.so.conf' && sudo ldconfig
  - sudo sysctl -w kernel.yama.ptrace_scope=0
  - sudo sh -c 'mkdir -p /etc/insights-client && echo -n 00000000-0000-0000-0000-000000000000 > /etc/insights-client/machine-id'

notifications:
  email: false
